name: learn-github-actions
run-name: Testing for commit with message ${{github.event.head_commit.message}}
on: [push]
jobs:
  check-jest-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g jest
      - run: jest --version